### ISSUE TITLE
Alt Key

### ISSUE THREAD

**Issue by adharstellosys** [shintadono/System.Windows.Forms.Ribbon#1]
Show alt key like Microsoft Office Word, First Show short cut keys of tabs, and when short cut key of tab is pressed show alt key of its buttons
![altkey](https://cloud.githubusercontent.com/assets/13160483/14243056/e6603a54-fa70-11e5-86d9-94da77a3340e.png)

**Comment by shintadono** [comment]
Thanks for the input, I was thinking about something on that line, too.... But this repo is merely a (slightly bugfixed) clone of the CodePlex Project http://officeribbon.codeplex.com . Try asking there.
